=== lllyyyme/vrmframework/src/main/java/org/vrmframework/dtd/ModelConfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pagemodel (datamodels,situation*)>
<!ELEMENT datamodels (datamodel*)>
<!ELEMENT datamodel EMPTY>
<!ELEMENT situation (field*)>
<!ELEMENT field EMPTY>


<!ATTLIST datamodel
        did  CDATA #REQUIRED
        dclass	 CDATA #REQUIRED>

<!ATTLIST pagemodel
        ref CDATA #REQUIRED>


<!ATTLIST situation
        sid  CDATA #REQUIRED
        sif	 CDATA #REQUIRED>

<!ATTLIST field
        fname    CDATA #REQUIRED
        fvalue   CDATA #REQUIRED
        v-ref    CDATA #REQUIRED
        byMethod CDATA #IMPLIED>

=== lllyyyme/vrmframework/src/main/java/com/application/xml/PersonPageModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pagemodel SYSTEM "E:\IdeaProjects\vrmframework\src\main\java\org\vrmframework\dtd\ModelConfig.dtd">
<pagemodel ref="com.application.realmodel.pagemodel.PersonPageModel" >


	<datamodels>
		<datamodel did = "familyServiceModel" dclass ="com.application.realmodel.datamodel.FamilyServiceModel"/>
	</datamodels>

	<rules>
		<rule rname="bPageRule" rclass ="com.application.rule.PersonPageRule"/>
	</rules>


	<situation sid="default"  sif="null">
		<field fname = "name" fvalue="{currApply.name}" v-ref="familyServiceModel"/>
		<field fname = "nation"   fvalue="{currApply.nation}"   v-ref="familyServiceModel" />
		<field fname = "sex" fvalue="{currApply.age}"    v-ref="familyServiceModel"/>
		<field fname = "birthDay" fvalue="{currApply.birthDay}" v-ref="familyServiceModel"/>
		<field fname = "work" fvalue="{currApply.work}" v-ref="familyServiceModel"/>
		<field fname = "school" fvalue="{currApply.school}" v-ref="familyServiceModel"/>
		<field fname = "disable" fvalue="true" v-ref=""/>
		<field fname = "check1" fvalue="true" v-ref=""/>
		<field fname = "check2" fvalue="false" v-ref=""/>
	</situation>

	<situation sid="s1" sif="bPageRule.hasUnderAge({0,rtype=java.lang.Integer})">
		<field fname = "name" fvalue="{currApply.name}" v-ref="familyServiceModel"/>
		<field fname = "nation"   fvalue="{currApply.nation}"   v-ref="familyServiceModel" />
		<field fname = "sex" fvalue="{currApply.age}"    v-ref="familyServiceModel"/>
		<field fname = "birthDay" fvalue="{currApply.birthDay}" v-ref="familyServiceModel"/>
		<field fname = "work" fvalue="{currApply.work}" v-ref="familyServiceModel"/>
		<field fname = "school" fvalue="{currApply.school}" v-ref="familyServiceModel"/>
		<field fname = "disable" fvalue="true" v-ref=""/>
		<field fname = "check1" fvalue="true" v-ref=""/>
		<field fname = "check2" fvalue="false" v-ref=""/>
		<field fname = "underAgeChildren" fvalue="{child}" v-ref="familyServiceModel" />


	</situation>



</pagemodel>

=== lllyyyme/vrmframework/src/main/java/com/application/xml/FamilyAdressPageModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pagemodel SYSTEM  "E:\IdeaProjects\vrmframework\src\main\java\org\vrmframework\dtd\ModelConfig.dtd">
<pagemodel ref="com.application.realmodel.pagemodel.FamilyAddressPageModel">



	<datamodels>
		<datamodel did = "familyServiceModel" dclass ="com.application.realmodel.datamodel.FamilyServiceModel"/>
	</datamodels>


	<situation sid="default" sif="null">
		<field fname = "street" fvalue="{address.street}" v-ref="familyServiceModel"/>
		<field fname = "province" fvalue="{address.province}" v-ref="familyServiceModel"/>
		<field fname = "city" fvalue="{address.city}" v-ref="familyServiceModel"/>
		<field fname = "county" fvalue="{address.county}" v-ref="familyServiceModel"/>
	</situation>

</pagemodel>
